### ISSUE TITLE
[Question] Size ≠ extent

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/gg#11]
The [comment at the beginning of the Sizes section](https://github.com/dbuenzli/gg/blob/master/src/gg.mli#L2140) saying "An n-dimensional {e size} [s] represents extents in n-dimensional space" seems misleading to me.  Indeed, at least in Cairo's parlance, an [extent is equivalent to a bounding box](https://cairographics.org/manual/cairo-Paths.html#cairo-path-extents).  Or is it ambiguous and *extent* should be explained rather than being used as an explanation! 😊

Maybe native English speakers could tell whether "extent" usually refers more to the "distance over which it extends" or also the location of the object?
/cc @avsm @dsheets @talex5 @yallop @amirmc

**Comment by dbuenzli** [comment]
This seems fine to me: 

http://www.merriam-webster.com/dictionary/extent
http://dictionary.cambridge.org/dictionary/english/extent

If any of the cc'ed english speaker has a better doc string. Speak.
