### ISSUE TITLE
Faster Float functions

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/gg#17]
Are you sure that the compiler does use the signature to specialize functions such as `Float.is_nan`?  I think adding a type annotation would be better/clearer, e.g.
```ocaml
let is_nan x = (x: float) <> x
```

**Comment by dbuenzli** [comment]
No I'm not.

**Comment by dbuenzli** [comment]
(also except for a few useful things I guess can largely deprecate the `Float` module)

**Comment by dbuenzli** [comment]
> Are you sure that the compiler does use the signature to specialize functions such as `Float.is_nan`?

The answer for a 4.03 compiler is no. It seems indeded that in the `Float` module there are a few places where I missed the annotations.

**Comment by dbuenzli** [comment]
> (also except for a few useful things I guess can largely deprecate the `Float` module)

This is tracked in https://github.com/dbuenzli/gg/issues/19
