### ISSUE TITLE
Have a function normalizing a vector but returning zero on zero

### ISSUE THREAD

**Issue by Armael** [dbuenzli/gg#2]
Hi,

Both of the times I used Gg, I found myself wanting {V2,V3}.unit to return {V2,V3}.zero on {V2,V3}.zero.
It's kind of a special case, but I think it is common in practice, so it would be useful to have a function ({V2,V3}.normalize ?) implementing this behavior.

What's your opinion about this?

-- Armael

**Comment by dbuenzli** [comment]
> but I think it is common in practice

Could you point to examples of this, a quick search fails at exhibiting what you want as common practice. Besides, what's your use case ? 

In general I'm not very fond of this, this seems like silently replacing a problem by a legitimate value which may end up making the problem harder to track in practice.

**Comment by Armael** [comment]
> Besides, what's your use case ? 
> Right. Hmm, right now it's something like "have some velocity vector; renormalize it; upscale it". It is ok to have a null velocity, in which case you just want not to move and return a null vector.

Well. This not a very striking example. Anyway, if you're not really fond of the idea, just close this. I do not have a strong opinion on whether the idea is good or not; was just asking.
