### ISSUE TITLE
`Gg.Box2.mem` does not satisfy its specification

### ISSUE THREAD

**Issue by francoisthire** [dbuenzli/gg#26]
My understanding of the specification should ensure that the following program always returns `true`, but if it is executed, we will see that most of the time it returns `false`. I expect this is related to floating point arithmetic.

```ocaml
Seq.ints 0 |> Seq.take 100 |> List.of_seq
    |> List.for_all (fun _ ->
           let x = Gg.P2.v (Random.float 10.) (Random.float 10.) in
           let y = Gg.P2.v (Random.float 10.) (Random.float 10.) in
           let box = Gg.Box2.of_pts x y in
           Gg.Box2.mem x box && Gg.Box2.mem y box )
```

For a concrete example, one can use the following snippet:
```ocaml
let x =
  Gg.P2.v 1.227721875450257238426843287016
                 1.217602532403128101634592894698
in
let y =
    Gg.P2.v 3.330991420098936561799973787856
                   0.148412743612841291351855943503
in
let box = Gg.Box2.of_pts x y in
Gg.Box2.mem x box && Gg.Box2.mem y box
```

Not sure how to fix that. Should we provide an optional `eps` argument to the `Gg.Box2.mem` function?

**Comment by francoisthire** [comment]
FYI: 

A fix I am using is to expand the box.

```ocaml
  let expand ?(eps = 0.00001) box =
    let mini = Gg.Box2.min box in
    let maxi = Gg.Box2.max box in
    let mini = Gg.P2.v (Gg.P2.x mini -. eps) (Gg.P2.y mini -. eps) in
    let maxi = Gg.P2.v (Gg.P2.x maxi +. eps) (Gg.P2.y maxi +. eps) in
    Gg.Box2.of_pts mini maxi
```

**Comment by dbuenzli** [comment]
It's not really surprising, `Box2.of_pts` converts the given points to a 2D point and a 2D size, there's a subtraction and you can loose precision there. I rather not add `eps` arguments to functions, it tends to be tricky to control and can get unwiedly over the code base. 

If you really care about the equation holding for the points used for constructing you should likely define your own `box2` type that defines a box by two points.

**Comment by francoisthire** [comment]
A suggestion could be to reflect this fact within the documentation.
