### ISSUE TITLE
Box2.subset seems wrong

### ISSUE THREAD

**Issue by Armael** [dbuenzli/gg#3]
```
# let big = Box2.v V2.zero (Size2.v 10. 10.);;
# let small = Box2.v (V2.v 100. 100.) (Size2.v 1. 1.);;
# Box2.subset small big;;
- : bool = true
```

(same issue with Box3.subset)

**Comment by dbuenzli** [comment]
Seems like an understatement. [That's](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L2044-L2047) [completely](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L2232-L2236) and [embarrassingly](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L2488-L2493) broken.

**Comment by dbuenzli** [comment]
Thanks for the report and sorry for that stupid bug. If you want to use the fix you can do:

```
opam pin add gg http://erratique.ch/repos/gg.git
```

until I make a new release.

**Comment by Armael** [comment]
Thanks!
