### ISSUE TITLE
Avoid overflow in the computation of norm

### ISSUE THREAD

**Issue by Chris00** [dbuenzli/gg#9]
The implementation of [norm](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L403) should use `hypot` to avoid overflow/underflow.  

For [V3.norm](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L403) and [V4.norm](https://github.com/dbuenzli/gg/blob/master/src/gg.ml#L607), should factor out the largest element in absolute value as [Complex.norm](https://github.com/ocaml/ocaml/blob/trunk/stdlib/complex.ml#L51).

**Comment by dbuenzli** [comment]
There was a problem on zero vectors which was fixed by 3cc0bca36d9253aa41e215c34047f410
